language: node_js
services:
  - 'docker'
node_js:
  - '16'
cache:
directories:
  - 'node_modules'
after_success:
  - docker-compose -p leviathan build
before_deploy:
  - docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD" docker.io ;
  - docker tag nestjs-products-api $DOCKER_USERNAME/leviathan:latest
deploy:
provider: script
script: docker push $DOCKER_USERNAME/leviathan:latest ;
notifications:
email: false
