version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    container_name: leviathan-db
    ports:
      - 5432:5432
    environment:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leviathan-api
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: leviathan-postgres
