version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    container_name: leviathan-db
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leviathan-api
    env_file:
      - .env
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db

volumes:
  postgres:
    name: leviathan-postgres
