version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: leviathan-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leviathan-api
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public'
    restart: always
    command: yarn run dev
    ports:
      - '4200:4200'
    depends_on:
      - db

volumes:
  postgres:
    name: leviathan-postgres
