version: '3.8'
services:
  api:
    container_name: leviathan-api-prod
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - postgres
    networks:
      - leviathan-network

  postgres:
    image: postgres:latest
    container_name: leviathan-postgres
    restart: always
    env_file:
      - .env.production
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - leviathan-network

  leviathan-nginx:
    container_name: leviathan-nginx
    restart: always
    build:
      context: docker/nginx
      dockerfile: docker/nginx/Dockerfile-nginx
    depends_on:
      - api
    ports:
      - '80:80'
    env_file:
      - .env.nginx
    networks:
      - leviathan-network

volumes:
  postgres_data:
    driver: local
networks:
  leviathan-network:
    driver: bridge
    name: leviathan-network
