version: '3.8'
services:
  db:
    image: 'mcr.microsoft.com/mssql/server'
    restart: always
    container_name: leviathan-db
    ports:
      - '1433:1433'
    env_file: .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leviathan-api
    env_file: .env
    restart: always
    ports:
      - 4200:4200
    depends_on:
      - db

volumes:
  postgres:
    name: leviathan-postgres
