version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leviathan-api
    env_file: .env
    restart: always
    command: yarn run start:dev
    ports:
      - '4200:4200'
    depends_on:
      - db

volumes:
  postgres:
    name: leviathan-postgres
