name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --immutable --frozen-lockfile

      - name: Build monorepo using Nx
        run: yarn nx affected --target build --parallel 2

      - name: Deploy to Vercel
        uses: vercel/action@v21
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          org-id: ${{ secrets.VERCEL_ORG_ID }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          prod-deployment-alias: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'my-prod-alias' || '' }}
          preview-deployment-alias: ${{ github.event_name == 'pull_request' && 'my-preview-alias-${{ github.event.pull_request.number }}' || '' }}
